spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu-qi/spring-cloud-config-f-lecture
          search-paths: config-repo
          username:   # 公共仓库可以不用用户名和密码
          password:
      label: master

server:
  port: 8763

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
